// src/config.js
export const GameConfig = {
    world: {
        gravity:     900,
        width:       1200,
        height:      800,
        viewWidth:   800,
        viewHeight:  600,
        wallThick:   20,
        wallColor:   0x4a4a4a,
        bgColor:     '#1a1a2e',
    },
    bouncyBall: {
        color:        0xff6600,
        bounce:       0.75,
        drag:         75,
        maxVelX:      400,
        maxVelY:      800,
        accel:        500,
        jumpVelocity: -450,
        landJumpVel:  -600,
        slamGravMult: 2.5,
    },
    metalBall: {
        color:        0xaaaaaa,
        bounce:       0.2,
        drag:         150,
        maxVelX:      300,
        maxVelY:      600,
        accel:        300,
        extraGravity: 600,
        jumpVelocity: -300,
        landJumpVel:  -300,
    },
    stickyBall: {
        color:         0x00cc44,
        bounce:        0,
        drag:          0,
        maxVelX:       400,
        maxVelY:       400,
        moveSpeed:     200,
        wallPush:      50,
        gravityCancel: -900,
    },
    audio: {
        bounceCooldown: 100,
    },
    ui: {
        titleY:         150,
        titleFontSize:  '72px',
        optionFontSize: '32px',
        optionStartY:   300,
        optionSpacing:  60,
        exitTextY:      400,
        exitFontSize:   '24px',
        selectedColor:  '#ffffff',
        defaultColor:   '#cccccc',
        selectedScale:  1.1,
        defaultScale:   1.0,
        cameraLerp:     0.1,
    },
    ball: {
        radius: 16,
    },
};
